### PR TITLE
Allow filtering injection types

### LINKED ISSUE #31: Allow specific web pages to opt out of autocomplete
Although the autocomplete feature is of great help, some websites might not want their users to use it in specific web pages.

Example:
if a user uses autocomplete superpowers in websites like codewars, leetcode or LiveCodes code challenges (specially if the time factor is important), it might be considered as cheating :) 
However, if the same website uses the editor in code tutorials, it might be desirable to enable the autocomplete.

My suggestion:

If a web page includes this meta tag, the autocomplete should not be activated in this specific web page even if the domain is in the allowlist:

```html
<meta name="codeium:type" content="none">
```

I expect if site owners have control over when to enable/disable the autocomplete, more websites are more likely to endorse it and tell the users about it (even as a feature).

If you agree to this approach, I can open a PR with the implementation, including the option to restrict injection type by the value of the `content` attribute as mentioned here: https://github.com/Exafunction/codeium-chrome/pull/29#pullrequestreview-1579608749

### PR DESCRIPTION
**Pull request by hatemhosny**
This PR allows filtering injection types or disabling the extension in specific web pages using a meta tag, as discussed in #29 and #31 

```html
<meta name="codeium:type" content="monaco" />
```

The `content` attribute accepts a comma-separated list of supported editors. These currently include: `"monaco"` and `"codemirror5"`.

To disable the extension in a specific page add the following meta tag:

```html
<meta name="codeium:type" content="none" />
```

closes #31

### CODE REVIEW

**Review by pqn — APPROVED** [review]
Looks like there are some merge conflicts to resolve.

**Comment by hatemhosny** [comment]
merge conflicts resolved 👍

thank you

**Review by pqn — APPROVED** [review]

**Comment by hatemhosny** [comment]
hi @pqn 
This is a gentle reminder. It seems that this version has not yet been published to chrome store, so that my users can use this feature.
Thank you.

**Comment by pqn** [comment]
It should be released now.

**Comment by hatemhosny** [comment]
Great, thank you

**Pull request merged**
